print('digite o primeiro numero complexo(x). ')
print('parte real: ')
a = float(input())
print('parte imaginaria: ')
b = float(input())
x = complex(a,b)
print(x)
print('parte real:' + str(x.real))
print('parte imaginaria: ' + str(x.imag))

print('\n\ndigite o segundo numero complexo(y). ')
print('parte real: ')
c = float(input())
print('parte imaginaria: ')
d = float(input())
y = complex(c,d)
print(y)
print('parte real:' + str(y.real))
print('parte imaginaria: ' + str(y.imag))

print('\n\ndigite o terceiro numero complexo(z). ')
print('parte real: ')
e = float(input())
print('parte imaginaria: ')
f = float(input())
z = complex(e,f)
print(z)
print('parte real:' + str(z.real))
print('parte imaginaria: ' + str(z.imag))

soma = x + y + z
print('\n\nsoma: ' + str(soma))
print('parte real:' + str(soma.real))
print('parte imaginaria: ' + str(soma.imag))
sub = x - y - z
print('\n\nsoma: ' + str(sub))
print('parte real:' + str(sub.real))
print('parte imaginaria: ' + str(sub.imag))
mult = x * y * z
print('\n\nsoma: ' + str(mult))
print('parte real:' + str(mult.real))
print('parte imaginaria: ' + str(mult.imag))
div = z / x
print('\n\nsoma: ' + str(div))
print('parte real:' + str(div.real))
print('parte imaginaria: ' + str(div.imag))
